const traitsList = { 
 "8-bit" : { breakpoints: { 2: [“#A0715E”, "5% per high score."], 4: [“#BD9A38”, "9% per high score."], 6: [“#BD9A38”, "14% per high score and unlock final high score, that rewards you with a grand prize."] }, 
			description: "Keep score of your team's damage dealt. For each high score you beat, 8-bit champions gain Attack Damage.", 
			logo: "https://rerollcdn.com/icons/8bit.png"},
  "Breakout" : { breakpoints: { 1:  [“#BD9A38”, "Bonus Effect"] }, 
			description: "(unique) Akali is a member of K/DA or True Damage depending on which Trait has more fielded champions. She gains a different Ability depending on which form she takes.", 
			logo: "https://rerollcdn.com/icons/breakout.png"},   
  "Country" : { breakpoints: { 3: [“#A0715E”, "Dreadsteed"], 5: [“#7D8F92”, "Midnight Dreadsteed"], 7: [“#BD9A38”, "Infernal Invocation Dreadsteed"] }, 
			description: "When your team loses 30% of their Health, call a Dreadsteed that empowers your team.<br /><br />Each Country star level increases its Health and Attack Damage.", 
			logo: "https://rerollcdn.com/icons/country.png"},
  "Disco" : { breakpoints: { 3: [“#A0715E”, "5% Attack Speed and 2% Max Health healing"], 4: [“#7D8F92”, "8% Attack Speed and 3% Max Health healing"], 5: [“#BD9A38”, "2 Disco Balls, 12% Attack Speed and 3% Max Health healing"], 6: ["#BD9A38", "20% Attack Speed and 4% Max Health healing"] }, 
			description: "Summon a moveable Disco Ball.<br /><br />Combat start: allies next to it gain Attack Speed and healing immediately and every 3 seconds.", 
			logo: "https://rerollcdn.com/icons/disco.png"},
  "EDM" : { breakpoints: { 2: [“#A0715E”, "90% effectiveness"], 3: [“#A0715E”, "100% effectiveness"], 4: [“#7D8F92”, "110% effectiveness, -1 second"], 5: ["#BD9A38", "130% effectiveness, -1 second"] }, 
			description: "Use the EDM selector to choose an EDM champion and see the frequency for each.<br /><br />At the selected champion's frequency, your EDM champions cast the selected abilities with modified effectiveness.", 
			logo: "https://rerollcdn.com/icons/edm.png"},
  "Emo" : { breakpoints: { 2: [“#A0715E”, "20% less, gain 20 Mana"], 4: [“#BD9A38”, "30% less, gain 30 Mana"], 6: [“#BD9A38”, "+10 AP, 40% less, gain 40 Mana"] }, 
			description: "Emo champions' abilities cost less Mana to cast, and they gain Mana whenever an allied champion dies.", 
			logo: "https://rerollcdn.com/icons/emo.png"},
  "Heartsteel" : { breakpoints: { 3: [“#A0715E”, "1x Hearts"], 5: [“#7D8F92”, "2.25x Hearts"], 7: [“#BD9A38”, "5.5x Hearts"], 10: ["#E5FFFF", "10x Hearts. Gain rewards every round and keep 80% of your hearts."] }, 
			description: "Earn Hearts by killing enemies. Gain even more by losing player combat. Every 4 player combats, convert Hearts into powerful rewards!", 
			logo: "https://rerollcdn.com/icons/heartsteel.png"},
  "Hyperpop" : { breakpoints: { 1: [“#A0715E”, "5 Mana and 10% Attack Speed"], 2: [“#BD9A38”, "10 Mana and 20% Attack Speed"], 3: [“#BD9A38”, "15 Mana and 35% Attack Speed"], 4: ["#BD9A38", "20 Mana and 60% Attack Speed"] }, 
			description: "When Hyperpop champions use an Ability, they grant Mana and 4 seconds of Attack Speed to their 2 closest allies.", 
			logo: "https://rerollcdn.com/icons/hyperpop.png"},   
  "ILLBEATS" : { breakpoints: { 1:  [“#BD9A38”, "Bonus Effect"] }, 
			description: "(unique) Gain 2/2/8 placeable Spirit Tentacles, based on Illaoi's star level. Tentacles gain Illaoi's bonus Armor and Magic Resist.", 
			logo: "https://rerollcdn.com/icons/illbeats.png"},  
  "Jazz" : { breakpoints: { 2: [“#A0715E”, "1.5% Health, 1% Damage"], 3: [“#7D8F92”, "2.5% Health, 1.5% Damage"], 4: [“#BD9A38”, "4% Health, 2% Damage"] }, 
			description: "For each active trait (except uniques), your team gains bonus Health and deals bonus damage.", 
			logo: "https://rerollcdn.com/icons/jazz.png"},
  "K/DA" : { breakpoints: { 3: [“#A0715E”, "+9% max Health, 9 AD, 9 AP"], 5: [“#7D8F92”, "+15% max Health, 15 AD, 15 AP"], 7: [“#BD9A38”, "+24% max Health, 24 AD, 24 AP"], 10: ["#E5FFFF", "+40% max Health, 40 AD, 40 AP, 10 Mana per second"] }, 
			description: "Your team gains max Health, Ability Power, and Attack Damage if they are in a lighted hex. K/DA champions gain double!", 
			logo: "https://rerollcdn.com/icons/kda.png"},
  "Maestro" : { breakpoints: { 1:  [“#BD9A38”, "Bonus Effect"] }, 
			description: "(unique) The Maestro always attacks at a fixed pace, converting 1% bonus Attack Speed into 0.7% Attack Damage.", 
			logo: "https://rerollcdn.com/icons/maestro.png"}, 
  "Mixmaster" : { breakpoints: { 1:  [“#BD9A38”, "Bonus Effect"] }, 
			description: "(unique) Choose a mode that changes the Mixmaster's attacks and Ability!", 
			logo: "https://rerollcdn.com/icons/mixmaster.png"}, 
  "Pentakill" : { breakpoints: { 3: [“#A0715E”, "15% bonus damage"], 5: [“#7D8F92”, "30% bonus damage"], 7: [“#BD9A38”, "45% bonus damage"], 10: ["#E5FFFF", "50% damage reduction and 99% bonus damage"] }, 
			description: "Pentakill champions reduce incoming damage by 15% and deal bonus damage. For each champion kill, a Pentakill champion rocks out and increases their damage bonus by 25%.<br /><br />On the 5th kill, all Pentakill champions rock out and your team gains 50% Attack Speed.", 
			logo: "https://rerollcdn.com/icons/pentakill.png"},
  "Punk" : { breakpoints: { 2: [“#A0715E”, "+180 Health and +18% Attack Damage"], 4: [“#BD9A38”, "+300 Health and +30% Attack Damage"], 6: [“#BD9A38”, "+450 Health and +45% Attack Damage"] }, 
			description: "Punks gain bonus Health and Attack Damage, which increases by 1% every time you spend gold on a Shop reroll.<br /><br />After Punks fight in combat, your 1st Shop reroll costs 1 gold and grants 3% bonus instead!", 
			logo: "https://rerollcdn.com/icons/punk.png"},
  "True Damage" : { breakpoints: { 2: [“#A0715E”, "15% damage"], 4: [“#7D8F92”, "30% damage"], 6: [“#BD9A38”, "45% damage"], 9: ["#E5FFFF", "99% damage, Bling Bonuses go Platinum!"] }, 
			description: "True Damage champions deal bonus true damage. If they are holding an item, they gain a unique Bling Bonus for their Ability.", 
			logo: "https://rerollcdn.com/icons/truedamage.png"},
  "Wildcard" : { breakpoints: { 1:  [“#BD9A38”, "Bonus Effect"] }, 
			description: "(unique) If you win player combat, Kayn becomes the Shadow Assassin. If not, he becomes Rhaast. You receive a reward based on his form every time he kills 2 enemy champions.<br /><br />Shadow Assassin: 3g<br /><br />Rhaast: 1 player health", 
			logo: "https://rerollcdn.com/icons/wildcard.png"}, 
  "Big Shot" : { breakpoints: { 2: [“#A0715E”, "10% Attack Damage, 40% after casting"], 4: [“#BD9A38”, "18% Attack Damage, 72% after casting"], 6: [“#BD9A38”, "30% Attack Damage, 120% after casting"]}, 
			description: "Big Shots gain Attack Damage, which increases for 3 seconds when they use their Ability.", 
			logo: "https://rerollcdn.com/icons/bigshot.png"},
  "Bruiser" : { breakpoints: { 2: [“#A0715E”, "20% max Health"], 4: [“#7D8F92”, "45% max Health"], 6: [“#BD9A38”, "90% max Health"] }, 
			description: "Your team gains 100 Health. Bruisers gain bonus max Health.", 
			logo: "https://rerollcdn.com/icons/bruiser.png"},
  "Crowd Diver" : { breakpoints: { 2: [“#A0715E”, "10% Attack Damage, 12% bonus damage"], 4: [“#BD9A38”, "30% bonus damage"], 6: [“#BD9A38”, "50% bonus damage"]}, 
			description: "After Crowd Divers die, they leap onto the furthest enemy, dealing 300 magic damage. Enemies within 1 hex are Stunned for 1.5 seconds<br /><br />They also deal bonus damage, increased by 1% each second.", 
			logo: "https://rerollcdn.com/icons/crowddiver.png"},
  "Dazzler" : { breakpoints: { 2: [“#A0715E”, "20% magic damage"], 4: [“#BD9A38”, "60% magic damage"], 6: [“#BD9A38”, "100% magic damage"] }, 
			description: "Dazzlers' Abilities reduce their target's damage by 10% and deal bonus magic damage over 2 seconds.", 
			logo: "https://rerollcdn.com/icons/dazzler.png"},
  "Edgelord" : { breakpoints: { 3: [“#A0715E”, "30% Attack Speed"], 5: [“#7D8F92”, "45% Attack Speed"], 7: [“#BD9A38”, "70% Attack Speed"] }, 
			description: "Edgelords gain Attack Speed, which doubles when their target drops below 50% Health. Edgelord with 1-hex range also dash through them on their next attack.", 
			logo: "https://rerollcdn.com/icons/edgelord.png"},
  "Executioner" : { breakpoints: { 2: [“#A0715E”, "5% Critical Strike Chance. Up to 25% Critical Strike Damage"], 4: [“#7D8F92”, "15% Critical Strike Chance. Up to 100% Critical Strike Damage"], 6: [“#BD9A38”, "30% Critical Strike Chance. Up to 200% Critical Strike Damage"] }, 
			description: "Executioner Abilities can critically strike and they gain Critical Strike Damage. Their Critical Strike Chance is increased base on their target's missing Health.", 
			logo: "https://rerollcdn.com/icons/executioner.png"},
  "Guardian" : { breakpoints: { 2: [“#A0715E”, "25%"], 4: [“#7D8F92”, "45%"], 6: [“#BD9A38”, "70%"] }, 
			description: "Once per combat at 50% Health, Guardians shield themselves and their closest ally for a percent of their max Health", 
			logo: "https://rerollcdn.com/icons/guardian.png"},
  "Mosher" : { breakpoints: { 2: [“#A0715E”, "20% Attack Speed, 10% Omnivamp"], 4: [“#7D8F92”, "40% Attack Speed, 15% Omnivamp"], 6: [“#BD9A38”, "70% Attack Speed, 20% Omnivamp"] }, 
			description: "Moshers gain Attack Speed and Omnivamp, which increases up to 100% based on their missing Health.", 
			logo: "https://rerollcdn.com/icons/mosher.png"},
  "Rapidfire" : { breakpoints: { 2: [“#A0715E”, "4% Attack Speed"], 4: [“#7D8F92”, "8% Attack Speed"], 6: [“#BD9A38”, "12% Attack Speed"] }, 
			description: "Your team gains 10% Attack Speed.<br /><br />Rapidfire champions gain more on every attack, up to 10 stacks.", 
			logo: "https://rerollcdn.com/icons/rapidfire.png"},
  "Sentinel" : { breakpoints: { 2: [“#A0715E”, "16 Armor, 16 Magic Resist"], 4: [“#7D8F92”, "35 Armor, 35 Magic Resist"], 6: [“#BD9A38”, "55 Armor, 55 Magic Resist"], 8: ["#E5FFFF", "100 Armor, 100 Magic Resist"] }, 
			description: "Your team gains Armor and Magic Resist. Sentinels gain double.", 
			logo: "https://rerollcdn.com/icons/sentinel.png"},
  "Spellweaver" : { breakpoints: { 3: [“#A0715E”, "+20 Ability Power, +1 Ability Power per cast"], 5: [“#7D8F92”, "+35 Ability Power, +2 Ability Power per cast"], 7: [“#BD9A38”, "+70 Ability Power, +3 Ability Power per cast"], 9: ["#BD9A38", "+120 Ability Power, +4 Ability Power per cast"] }, 
			description: "Your team gains 15 Ability Power. Spellweavers gain more, plus extra Ability Power whenever a Spellweaver casts an Ability.", 
			logo: "https://rerollcdn.com/icons/spellweaver.png"},
  "Superfan" : { breakpoints: { 3: [“#A0715E”, "Headliner gets a completed item"], 4: [“#7D8F92”, "Headliner gets 250 Health and 15% Omnivamp"], 5: [“#BD9A38”, "Item upgrades to radiant"] }, 
			description: "Superfans improve your headliner!", 
			logo: "https://rerollcdn.com/icons/superfan.png"}			
}	
			
			


			
			